name: reviewdog
on: [ pull_request ]
jobs:
  pyright:
    name: pyright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wemake-services/wemake-python-styleguide
        with:
          reporter: github-pr-review