name: reviewdog
on: [ pull_request ]
jobs:
  wemake-python-styleguide:
    name: wemake-python-styleguide
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.17.0
        with:
          reporter: github-pr-review